services:
  postgres:
    container_name: postgres-chat
    image: postgres
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: chat
    volumes:
      - postgres:/data/postgres
    ports:
      - "5433:5432"
    networks:
      - chat
    restart: unless-stopped
  keycloak:
    container_name: keycloak-chat
    image: quay.io/keycloak/keycloak:26.0.0
    ports:
      - "9090:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    networks:
      - chat
    command:
      - "start-dev"

networks:
  chat:
    driver: bridge


volumes:
  postgres:
    driver: local
  keycloak:
    driver: local