spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    web: debug

